### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by 73567876543783** [jhelvy/splitKbCompare#78]
Plate file available, need to add:
- [ ] manibus
- [ ] avalanche
- [ ] lotus58
- [ ] hillside

Still need plate file:
- [ ] Apoptosis (#45)
- [ ] Matias Ergo Pro: https://matias.ca/ergopro/pc/
- [ ] pinky4 (#18)
- [ ] chimera42
- [ ] orthodox
- [ ] centrometre

Features:
- [ ] Filter the DT in the Keyboards pane based on the filters of the compare pane. Adding a switch on the Keyboards pane to decide if you want to use the filters from the compare pane or show all
- [ ] Add an open-source filter
- [ ] Add "open image in new tab" button
- [ ] Add single instead of multiple select? (#39)
- [ ] Consider reducing the image size for speed?

**Comment by splitkb** [comment]
For the last todo, would it alleviate the issue if you'd move to a paid plan? I'd be happy to sponsor, feel free to reach out if interested :)

**Comment by jhelvy** [comment]
Thanks for the offer Thomas. I'm not 100% certain if having a paid plan with more power on the backend would solve the issue, but it might. You could always try it by getting a paid plan on shinyapps.io and hosting it there. All the source files are in this repo. At least we'd learn if that solves it.

**Comment by jhelvy** [comment]
My suspicion is that having more computing power would solve it. Check out the app usage - it's fully pegged out almost every day.
![Screen Shot 2022-01-15 at 9 48 38 AM](https://user-images.githubusercontent.com/9012994/149626104-9c9abc68-08f8-4bac-9a74-bc1f241f1c0e.png)
